const request = require('supertest');
const mongoose = require('mongoose');
const app = require('../app');
const { connect, clearDatabase, closeDatabase } = require('./setup');
const { ModerationLog, ModerationAction } = require('../models/ModerationLog.model');
const { User, UserRole } = require('../models/User.model');

describe('Moderation Log Module', () => {
    let adminToken;
    let moderatorToken;
    let userToken;
    let adminId;
    let moderatorId;
    let targetUserId;

    beforeAll(async () => {
        await connect();
    });

    afterEach(async () => {
        await clearDatabase();
    });

    afterAll(async () => {
        await closeDatabase();
    });

    beforeEach(async () => {
        // Create users
        const password = 'Password123!';
        
        const admin = await User.create({
            name: 'Admin User',
            email: `admin_${Date.now()}@app.com`,
            password,
            role: UserRole.ADMIN
        });
        adminId = admin._id.toString();

        const mod = await User.create({
            name: 'Moderator User',
            email: `mod_${Date.now()}@app.com`,
            password,
            role: UserRole.MODERATOR
        });
        moderatorId = mod._id.toString();

        const standardUser = await User.create({
            name: 'Standard User',
            email: `user_${Date.now()}@app.com`,
            password,
            role: UserRole.USER
        });
        targetUserId = standardUser._id.toString();

        // Login Admin
        let res = await request(app).post('/api/v1/auth/login').send({ email: admin.email, password });
        adminToken = res.body.data.token;

        // Login Moderator
        res = await request(app).post('/api/v1/auth/login').send({ email: mod.email, password });
        moderatorToken = res.body.data.token;

        // Login Standard User
        res = await request(app).post('/api/v1/auth/login').send({ email: standardUser.email, password });
        userToken = res.body.data.token;
    });

    describe('GET /api/v1/moderation/logs', () => {
        beforeEach(async () => {
            // Clear any moderation logs generated by login events
            await ModerationLog.deleteMany({});
            
            // Seed Moderation Logs
            await ModerationLog.create([
                {
                    action: ModerationAction.BAN,
                    moderatorId: adminId,
                    targetUserId: targetUserId,
                    reason: 'Spamming reports',
                },
                {
                    action: ModerationAction.APPROVE,
                    moderatorId: moderatorId,
                    reportId: new mongoose.Types.ObjectId(),
                    reason: 'Looks verified'
                },
                {
                    action: ModerationAction.REJECT,
                    moderatorId: moderatorId,
                    reportId: new mongoose.Types.ObjectId(),
                    reason: 'Fake location'
                }
            ]);
        });

        it('should allow ADMIN to fetch moderation logs', async () => {
            const res = await request(app)
                .get('/api/v1/moderation/logs')
                .set('Authorization', `Bearer ${adminToken}`);

            expect(res.status).toBe(200);
            expect(res.body.data.logs).toHaveLength(3);
            expect(res.body.data.pagination).toBeDefined();
        });

        it('should allow MODERATOR to fetch moderation logs', async () => {
            const res = await request(app)
                .get('/api/v1/moderation/logs')
                .set('Authorization', `Bearer ${moderatorToken}`);

            expect(res.status).toBe(200);
            expect(res.body.data.logs).toHaveLength(3);
        });

        it('should forbid STANDARD USER from fetching logs', async () => {
            const res = await request(app)
                .get('/api/v1/moderation/logs')
                .set('Authorization', `Bearer ${userToken}`);

            expect(res.status).toBe(403);
            expect(res.body.message).toMatch(/Access denied/i);
        });

        it('should filter logs by action query param', async () => {
            const res = await request(app)
                .get('/api/v1/moderation/logs?action=APPROVE')
                .set('Authorization', `Bearer ${adminToken}`);

            expect(res.status).toBe(200);
            expect(res.body.data.logs).toHaveLength(1);
            expect(res.body.data.logs[0].action).toBe(ModerationAction.APPROVE);
        });

        it('should filter logs by moderatorId query param', async () => {
            const res = await request(app)
                .get(`/api/v1/moderation/logs?moderatorId=${moderatorId}`)
                .set('Authorization', `Bearer ${adminToken}`);

            expect(res.status).toBe(200);
            expect(res.body.data.logs).toHaveLength(2); // Moderator approved & rejected 1 report each
        });

        it('should paginate correctly', async () => {
            const res = await request(app)
                .get('/api/v1/moderation/logs?page=1&limit=2')
                .set('Authorization', `Bearer ${adminToken}`);

            expect(res.status).toBe(200);
            expect(res.body.data.logs).toHaveLength(2);
            expect(res.body.data.pagination.total).toBe(3);
            expect(res.body.data.pagination.pages).toBe(2);
        });
    });
});
